### ISSUE TITLE
Why is the text upside down?

### ISSUE THREAD

**Issue by bebetoalves** [TypesettingTools/Perspective#2]
Print: http://i.imgur.com/8Ay9pwr.png

**Comment by Zeght** [comment]
1. Don't expect good answers with that kind of report. For all I know, you could've set it upside-down yourself.
2. It's just a single word and perspective is pretty simple. In such cases it's usually faster to set perspective manually.
3. You probably listed points of tetragon in the wrong order. It should be listed clockwise, starting from top-left (seems like you did it counterclockwise starting with wrong point).
