### ISSUE TITLE
Current regex doesn't handle negative coordinates

### ISSUE THREAD

**Issue by OrangeChannel** [TypesettingTools/Perspective#3]
I saw someone get reccomended this script the other day over the moonscript version and remembered that I had found an issue a few months ago.

https://github.com/TypesettingTools/Perspective/blob/64fa643d5f3e594c1bbe92c5bd0b9d6614bca6c9/perspective.py#L179

Should be `[-\d\.]+`

Input: `"116 490 l 1700 -120 1757 818 82 978"`

| Before       |       After |
|-------------- |------------|
|`Transforms near center of tetragon: Ratio=2.952823 \org(1286.8, 1113.3)\fry-3.88\frx1.44\frz2.40`|`Transforms near center of tetragon: Ratio=2.591684 \org(1052.9, 1114.2)\fry-6.84\frx1.32\frz0.45`|
|`Transforms with target ratio: Ratio=3.325362 \org(1769.0, 876.2)\fry-3.57\frx1.32\frz4.80`|`Transforms with target ratio: Ratio=3.469750 \org(1885.8, 884.3)\fry-5.26\frx1.02\frz4.14`|

---

`"0 0 0 200 600 300 600 -100"` gives "No proper perspective found." originally, but finds both transforms with the added negative sign.

**Comment by Zeght** [comment]
Thanks for reporting. Fixed.
